"""Init database tables

Revision ID: ea24a0a69458
Revises:
Create Date: 2025-02-02 12:54:49.197173

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea24a0a69458"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("block_number", sa.BigInteger(), nullable=False),
        sa.Column("tx_from", sa.String(), nullable=False),
        sa.Column("tx_to", sa.String(), nullable=True),
        sa.Column("value", sa.Numeric(precision=50), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    # ### end Alembic commands ###
